baseURL = 'https://leoters.github.io'
locale = 'en-us'
title = 'Pedro Leote'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[params]
  customCSS = ["css/extended/custom.css"]
  
  [params.label]
    text = ""

  [params.contact]
    email = 'pedro_leote@eticalgarve.com'

  [[params.socialIcons]]
    name = "itchio"
    url = "https://leoters.itch.io/"

  [[params.socialIcons]]
    name = "Email"
    url = "mailto:pedro_leote@eticalgarve.com"

  [[params.socialIcons]]
    name = "LinkedIn"
    url = "https://linkedin.com/in/leoters"
    
  [[params.socialIcons]]
    name = "Bluesky"
    url = "https://bsky.app/profile/leoters.bsky.social"

  

  [params.profileMode]
    enabled = true
    title = "Pedro Leote"
    subtitle = "Tech Artist | VFX Artist"
    imageUrl = "images/profile.jpg"
    imageTitle = "Pedro Leote"
    imageWidth = 240
    imageHeight = 240

    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/posts"

    [[params.profileMode.buttons]]
      name = "Portfolio"
      url = "/portfolio"


  
