baseURL = 'https://leoters.github.io'
locale = 'en-us'
title = 'Pedro Leote'
theme = 'PaperMod'
sectionPagesMenu = 'main'

[params]
  customCSS = ["css/extended/custom.css"]
  
  [params.label]
    text = ""

  [params.contact]
    email = 'pedro_leote@eticalgarve.com'


  [params.profileMode]
    enabled = true
    title = "Pedro Leote"
    subtitle = "Tech Artist | VFX Artist"
    imageUrl = "images/profile.jpg"
    imageTitle = "Pedro Leote"
    imageWidth = 240
    imageHeight = 240

    [[params.profileMode.buttons]]
      name = "Blog"
      url = "/posts"

    [[params.profileMode.buttons]]
      name = "Portfolio"
      url = "/portfolio"


  
